### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Rukeith** [chrisjpatty/create-react-redux-router-app#1]
I use this to generate a my-app project and run `yarn start`.
It show up this at website.
<img width="1056" alt="screen shot 2017-11-09 at 16 51 14" src="https://user-images.githubusercontent.com/7069605/32596462-521bf8d6-c56e-11e7-83fd-07cd96fdbd8b.png">

**Comment by chrisjpatty** [comment]
Hm, I haven't had a chance to update it for React 16. I'll take a look at it and get a fix pushed out. Thanks for letting me know!

**Comment by ahmadawais** [comment]
I have the same error. 

![image](http://on.ahmda.ws/ni1N/c)

Had this failed to compile error while installing

![image](http://on.ahmda.ws/nj3G/c)

**Comment by ahmadawais** [comment]
This is what happens in the install process

```sh
Installing redux, react-router, react-router-dom, react-redux, and redux-thunk

/bin/sh: yarn: command not found

Finished installing packages
```

**Comment by ahmadawais** [comment]
I think it's coz of this line
https://github.com/chrisjpatty/create-react-redux-router-app/blob/b9d2ca0038558fba4c955b8dfa9f3898f4018595/index.js#L48

You're assuming we have `yarn` installed.

**Comment by chrisjpatty** [comment]
@Rukeith I've pushed a new release to npm that should fix this issue for you. Just run a global upgrade on the package. Let me know if you have any more issues! Thanks again @ahmadawais for the pull request!
