### ISSUE TITLE
This no longer works? -- Failed to Compile error

### ISSUE THREAD

**Issue by jasonkv** [chrisjpatty/create-react-redux-router-app#3]
Everything seems to install fine, tried doing `npm install` and `npm start` and I get this when it opens up the browser:

./src/index.js
Module not found: Can't resolve './registerServiceWorker' in

**Comment by chrisjpatty** [comment]
Thanks for trying it out @jasonkv! It's likely that create-react-app 2.0 has broken this generator. This project is about a year old, which in Javascript years is a whole century, so I don't know that I would even recommend using it anymore. I've been meaning to rewrite it entirely so it's a little more configurable and will automatically adjust to future versions of create-react-app. If you're up for it I would certain welcome pull requests.
